# Generated by Django 4.2 on 2023-04-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_slug',
            old_fields=('id', 'slug'),
        ),
    ]
