# Generated by Django 4.2 on 2023-05-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
